<?php
// $Id: xmlsitemap_engines.install,v 1.3.2.6.2.5 2009/05/16 05:42:32 davereid Exp $

/**
 * @file
 * Install and uninstall schema and functions for the xmlsitemap_engines module.
 */

/**
 * Implementation of hook_uninstall().
 */
function xmlsitemap_engines_uninstall() {
  // Remove variables.
  drupal_load('module', 'xmlsitemap_engines');
  $variables = array_keys(xmlsitemap_engines_variables());
  foreach ($variables as $variable) {
    variable_del($variable);
  }
}
