<?php
// $Id: session_limit.install,v 1.2 2008/12/04 16:30:13 deekayen Exp $

/**
 * @file
 * Contains install and update functions for Session Limit.
 *
 * @ingroup session_limit
 */

/**
 * Implementation of hook_uninstall().
 */
function session_limit_uninstall() {
  variable_del('session_limit_max');
  variable_del('session_limit_auto_drop');
  variable_del('session_limit_masquerade_ignore');
}
