<?php

function own_buy_menu() {
  $items['own_buy'] = array(
    'title' => 'Omat ostoilmoitukset',
    'page callback' => 'own_buy_page',
    'page arguments' => array(1),
    'access callback' => 'own_buy_access',
    'access arguments' => array(1, 3, 'view'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function own_buy_access() {
  return user_access('access own buy page');
}

function own_buy_perm() {
  return array('access own buy page');
}

function own_buy_page() {

  global $user;

  $list_length = 5;
  $tid = "1";
  $teaser_length = 150;

  if(in_array(utf8_encode('ylläpitäjä'), $user->roles)) {
   
  $query = "SELECT n.nid" .
          " FROM {node} AS n where type='ostoilmoitukset'";
  }
  else {
  
  $query = "SELECT n.nid" .
          " FROM {node} AS n where type='ostoilmoitukset' and uid = '" . $user->uid . "'";
  }

  $result = pager_query($query, $list_length);

  $output = '';
  while ($item = db_fetch_object($result)) {
    $aNode['nid'] = $item->nid;
    $node = node_load($aNode);
    $output .= "<h2 class='title'><br/>";
    $output .= l($node->title, 'node/' . $node->nid);
    $output .= "</h2><br/>";
    $output .= "<div class='tables2'>";
    $output .= $node->body . "<br/><br/><div width='100%' style='margin-right: 20px;' align='right'>";
    $output .= l('Näytä koko ilmoitus', 'node/' . $node->nid);    
    $output .= "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
    $output .= l('Muokkaa tai poista', 'node/' . $node->nid . '/edit');    
    $output .= "</div></div>";
  }

  print theme('page', $output);
  
}