<?php

function own_content_menu() {
  $items['own_content'] = array(
    'title' => 'Omat myytävät kohteet',
    'page callback' => 'own_content_page',
    'page arguments' => array(1),
    'access callback' => 'own_content_access',
    'access arguments' => array(1, 3, 'view'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function own_content_access() {
  return user_access('access content') && user_access('access own content page');
}

function own_content_perm() {
  return array('access own content page');
}

function own_content_page() {

  global $user;

  $list_length = 5;
  $tid = "1";
  $teaser_length = 150;

  if(in_array('ylläpitäjä', $user->roles)) {
    
  $query = "SELECT n.nid" .
          " FROM {node} AS n where type='myytava_kohde'";
  }
  else {
  
  $query = "SELECT n.nid" .
          " FROM {node} AS n where type='myytava_kohde' and uid = '" . $user->uid . "'";
  }

  $result = db_query($query, $list_length);

  $output = '';
  while ($item = db_fetch_object($result)) {
    $aNode['nid'] = $item->nid;
    $node = node_load($aNode);
    
    $output .= "<h2 class='title'><br/>";
    $output .= l($node->title, 'node/' . $node->nid);
    $output .= "</h2>";
    $output .= "<div style='background: #cee4f2; padding: 10px;'>";
    $output .= $node->body . "<br/><br/><div width='100%' style='margin-right: 20px;' align='right'>";

    if((($node->uid == $user->uid) || (in_array('ylläpitäjä', $user->roles))) && ($node->status == 0)) {

	$output .= "<font color='red' style='padding-right: 274px; font-size: 10px;'><i>Odottaa hyväksyntää</i></font>";
    }

    $output .= l('Näytä koko ilmoitus', 'node/' . $node->nid);    
    $output .= "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
    $output .= l('Muokkaa', 'node/' . $node->nid . '/edit');    
    $output .= "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
    $output .= l('Poista', 'node/' . $node->nid . '/delete');    
    $output .= "</div></div>";
  }

  print theme('page', $output);
  
}