<?php
// vim: set filetype=php expandtab tabstop=2 shiftwidth=2 autoindent smartindent:
// $Id: view_own.install,v 1.1 2008/09/01 10:31:32 djuba Exp $

/**
 * @file
 * Installation of view_own module
 * 
 */

/**
 * Implementation of hook_install().
 */
function view_own_install() {
  // this module do not needs special schema
}

/**
 * Implementation of hook_uninstall().
 */
function view_own_uninstall() {
}

